/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard/transactions'
import { Route as DashboardSubscriptionsRouteImport } from './routes/dashboard/subscriptions'
import { Route as DashboardP2pIndexRouteImport } from './routes/dashboard/p2p/index'
import { Route as DashboardP2pSharedRouteImport } from './routes/dashboard/p2p/shared'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/dashboard/transactions',
  path: '/dashboard/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubscriptionsRoute = DashboardSubscriptionsRouteImport.update({
  id: '/dashboard/subscriptions',
  path: '/dashboard/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardP2pIndexRoute = DashboardP2pIndexRouteImport.update({
  id: '/dashboard/p2p/',
  path: '/dashboard/p2p/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardP2pSharedRoute = DashboardP2pSharedRouteImport.update({
  id: '/dashboard/p2p/shared',
  path: '/dashboard/p2p/shared',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/p2p/shared': typeof DashboardP2pSharedRoute
  '/dashboard/p2p/': typeof DashboardP2pIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/p2p/shared': typeof DashboardP2pSharedRoute
  '/dashboard/p2p': typeof DashboardP2pIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/p2p/shared': typeof DashboardP2pSharedRoute
  '/dashboard/p2p/': typeof DashboardP2pIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/subscriptions'
    | '/dashboard/transactions'
    | '/dashboard/'
    | '/dashboard/p2p/shared'
    | '/dashboard/p2p/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/subscriptions'
    | '/dashboard/transactions'
    | '/dashboard'
    | '/dashboard/p2p/shared'
    | '/dashboard/p2p'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/subscriptions'
    | '/dashboard/transactions'
    | '/dashboard/'
    | '/dashboard/p2p/shared'
    | '/dashboard/p2p/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DashboardSubscriptionsRoute: typeof DashboardSubscriptionsRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardP2pSharedRoute: typeof DashboardP2pSharedRoute
  DashboardP2pIndexRoute: typeof DashboardP2pIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subscriptions': {
      id: '/dashboard/subscriptions'
      path: '/dashboard/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof DashboardSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/p2p/': {
      id: '/dashboard/p2p/'
      path: '/dashboard/p2p'
      fullPath: '/dashboard/p2p/'
      preLoaderRoute: typeof DashboardP2pIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/p2p/shared': {
      id: '/dashboard/p2p/shared'
      path: '/dashboard/p2p/shared'
      fullPath: '/dashboard/p2p/shared'
      preLoaderRoute: typeof DashboardP2pSharedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DashboardSubscriptionsRoute: DashboardSubscriptionsRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardP2pSharedRoute: DashboardP2pSharedRoute,
  DashboardP2pIndexRoute: DashboardP2pIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
