//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "accounts"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "Account",
    export_to = "../../../packages/types/src/db/Account.ts"
)]
pub struct Model {
    pub id: String,
    pub account_id: String,
    pub provider_id: String,
    pub user_id: String,
    pub access_token: Option<String>,
    pub refresh_token: Option<String>,
    pub id_token: Option<String>,
    pub access_token_expires_at: Option<DateTimeWithTimeZone>,
    pub refresh_token_expires_at: Option<DateTimeWithTimeZone>,
    pub scope: Option<String>,
    pub password: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    AccountId,
    ProviderId,
    UserId,
    AccessToken,
    RefreshToken,
    IdToken,
    AccessTokenExpiresAt,
    RefreshTokenExpiresAt,
    Scope,
    Password,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::String(StringLen::None).def().null(),
            Self::AccountId => ColumnType::String(StringLen::None).def(),
            Self::ProviderId => ColumnType::String(StringLen::None).def(),
            Self::UserId => ColumnType::String(StringLen::None).def(),
            Self::AccessToken => ColumnType::String(StringLen::None).def().null(),
            Self::RefreshToken => ColumnType::String(StringLen::None).def().null(),
            Self::IdToken => ColumnType::String(StringLen::None).def().null(),
            Self::AccessTokenExpiresAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::RefreshTokenExpiresAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::Scope => ColumnType::String(StringLen::None).def().null(),
            Self::Password => ColumnType::String(StringLen::None).def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
