//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use ts_rs::TS;

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, TS)]
#[sea_orm(table_name = "bank_statement_rows")]
#[ts(export, rename = "BankStatementRow", export_to = "../../../packages/types/src/db/generated.ts")]

pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub date: DateTimeWithTimeZone,
    pub description: String,
    #[ts(type = "string | null")]
    pub debit: Option<Decimal>,
    #[ts(type = "string | null")]
    pub credit: Option<Decimal>,
    #[ts(type = "string")]
    pub balance: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::statement_txn_matches::Entity")]
    StatementTxnMatches,
}

impl Related<super::statement_txn_matches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StatementTxnMatches.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        super::statement_txn_matches::Relation::Transactions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::statement_txn_matches::Relation::BankStatementRows
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
