//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use ts_rs::TS;

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, TS)]
#[sea_orm(table_name = "contacts")]
#[ts(export, rename = "Contact", export_to = "../../../packages/types/src/db/generated.ts")]

pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub phone: Option<String>,
    pub is_pinned: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contact_identifiers::Entity")]
    ContactIdentifiers,
    #[sea_orm(has_many = "super::contact_links::Entity")]
    ContactLinks,
}

impl Related<super::contact_identifiers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContactIdentifiers.def()
    }
}

impl Related<super::contact_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContactLinks.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::contact_links::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::contact_links::Relation::Contacts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
