//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "statement_txn_matches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub row_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub transaction_id: String,
    pub confidence: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bank_statement_rows::Entity",
        from = "Column::RowId",
        to = "super::bank_statement_rows::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    BankStatementRows,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::TransactionId",
        to = "super::transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transactions,
}

impl Related<super::bank_statement_rows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BankStatementRows.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
