//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "subscriptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: String,
    pub name: String,
    pub amount: Decimal,
    pub cycle: String,
    pub start_date: DateTimeWithTimeZone,
    pub next_charge_date: DateTimeWithTimeZone,
    pub detection_keywords: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sub_alerts::Entity")]
    SubAlerts,
    #[sea_orm(has_many = "super::subscription_charges::Entity")]
    SubscriptionCharges,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::sub_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubAlerts.def()
    }
}

impl Related<super::subscription_charges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionCharges.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
