//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::enums::{TransactionDirection, TransactionSource, TransactionStatus};

use sea_orm::entity::prelude::*;
use ts_rs::TS;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, TS)]
#[sea_orm(table_name = "transactions")]
#[ts(export, rename = "Transaction", export_to = "../../../packages/types/src/db/generated.ts")]

pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: String,
    #[ts(type = "string")]
    pub amount: Decimal,
    pub direction: TransactionDirection,
    pub date: DateTimeWithTimeZone,
    pub source: TransactionSource,
    pub status: TransactionStatus,
    pub purpose_tag: Option<String>,
    pub group_id: Option<String>,
    pub source_wallet_id: Option<String>,
    pub destination_wallet_id: Option<String>,
    pub ledger_tab_id: Option<String>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::p2p_transfers::Entity")]
    P2pTransfers,
    #[sea_orm(has_many = "super::purchases::Entity")]
    Purchases,
    #[sea_orm(has_many = "super::statement_txn_matches::Entity")]
    StatementTxnMatches,
    #[sea_orm(has_many = "super::transaction_edits::Entity")]
    TransactionEdits,
    #[sea_orm(has_one = "super::transaction_metadata::Entity")]
    TransactionMetadata,
    #[sea_orm(has_many = "super::transaction_sources::Entity")]
    TransactionSources,
    #[sea_orm(has_many = "super::txn_parties::Entity")]
    TxnParties,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::p2p_transfers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::P2pTransfers.def()
    }
}

impl Related<super::purchases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Purchases.def()
    }
}

impl Related<super::statement_txn_matches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StatementTxnMatches.def()
    }
}

impl Related<super::transaction_edits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionEdits.def()
    }
}

impl Related<super::transaction_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionMetadata.def()
    }
}

impl Related<super::transaction_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionSources.def()
    }
}

impl Related<super::txn_parties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TxnParties.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::bank_statement_rows::Entity> for Entity {
    fn to() -> RelationDef {
        super::statement_txn_matches::Relation::BankStatementRows.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::statement_txn_matches::Relation::Transactions
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
