//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::enums::GroupRole;

use sea_orm::entity::prelude::*;
use ts_rs::TS;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, TS)]
#[sea_orm(table_name = "users")]
#[ts(export, rename = "User", export_to = "../../../packages/types/src/db/generated.ts")]

pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub email_verified: bool,
    pub image: Option<String>,
    pub phone: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub username: Option<String>,
    pub display_username: Option<String>,
    pub role: Option<GroupRole>,
    pub banned: Option<bool>,
    pub ban_reason: Option<String>,
    pub ban_expires: Option<DateTimeWithTimeZone>,
    pub two_factor_enabled: Option<bool>,
    pub phone_number: Option<String>,
    pub phone_number_verified: Option<bool>,
    #[ts(type = "any")]
    pub metadata: Option<Json>,
    pub associated_contact_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::accounts::Entity")]
    Accounts,
    #[sea_orm(has_many = "super::contact_links::Entity")]
    ContactLinks,
    #[sea_orm(has_many = "super::ledger_tabs::Entity")]
    LedgerTabs,
    #[sea_orm(has_many = "super::p2p_requests::Entity")]
    P2pRequests,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::subscriptions::Entity")]
    Subscriptions,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
    #[sea_orm(has_many = "super::user_groups::Entity")]
    UserGroups,
    #[sea_orm(has_many = "super::user_upi_ids::Entity")]
    UserUpiIds,
    #[sea_orm(has_many = "super::wallets::Entity")]
    Wallets,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::contact_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContactLinks.def()
    }
}

impl Related<super::ledger_tabs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerTabs.def()
    }
}

impl Related<super::p2p_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::P2pRequests.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriptions.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGroups.def()
    }
}

impl Related<super::user_upi_ids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserUpiIds.def()
    }
}

impl Related<super::wallets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallets.def()
    }
}

impl Related<super::contacts::Entity> for Entity {
    fn to() -> RelationDef {
        super::contact_links::Relation::Contacts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::contact_links::Relation::Users.def().rev())
    }
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_groups::Relation::Groups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_groups::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
