// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AggregatedMetrics = { total_income: string, total_expense: string, net_balance: string, count: number, };
