// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetPeriod } from "./BudgetPeriod";

export type Budget = { id: string, user_id: string, category_id: string | null, amount: string, period: BudgetPeriod, created_at: string, updated_at: string, };
