// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetPeriod } from "./BudgetPeriod";

export type BudgetHealth = { budget_id: string, category_name: string | null, limit_amount: string, spent_amount: string, remaining_amount: string, percentage_consumed: string, period: BudgetPeriod, };
