// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";

export type ContactStaging = { id: string, user_id: string, ocr_job_id: string, name: string, phone: string | null, email: string | null, upi_id: string | null, status: string, candidates: JsonValue | null, created_at: string, updated_at: string, };
