// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Contact } from "./Contact";
import type { ContactIdentifier } from "./ContactIdentifier";
import type { Transaction } from "./Transaction";

export type ContactDetail = { contact: Contact, identifiers: Array<ContactIdentifier>, transactions: Array<Transaction>, };
