// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactIdentifier = { id: string, contact_id: string, type: string, value: string, linked_user_id: string | null, };
