// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DetectedSubscription = { name: string, amount: string, cycle: string, last_date: string, count: number, };
