// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Account = { id: string, account_id: string, provider_id: string, user_id: string, access_token: string | null, refresh_token: string | null, id_token: string | null, access_token_expires_at: string | null, refresh_token_expires_at: string | null, scope: string | null, password: string | null, created_at: string, updated_at: string, };

export type AlertChannel = "EMAIL" | "PUSH";

export type BankStatementRow = { id: string, date: string, description: string, debit: string | null, credit: string | null, balance: string, };

export type Contact = { id: string, name: string, phone: string | null, is_pinned: boolean, };

export type ContactIdentifier = { id: string, contact_id: string, type: string, value: string, linked_user_id: string | null, };

export type ContactLink = { user_id: string, contact_id: string, };

export type Group = { id: string, name: string, description: string | null, created_at: string, };

export type GroupRole = "ADMIN" | "MEMBER";

export type IdentifierType = "UPI" | "PHONE" | "BANK_ACC";

export type LedgerTab = { id: string, creator_id: string, counterparty_id: string | null, tab_type: string, title: string, target_amount: string, status: string, created_at: string, updated_at: string, };

export type LedgerTabStatus = "OPEN" | "PARTIALLY_PAID" | "SETTLED";

export type LedgerTabType = "LENT" | "BORROWED";

export type P2PRequest = { id: string, sender_user_id: string, receiver_email: string, transaction_data: any, status: string, linked_txn_id: string | null, };

export type P2PRequestStatus = "PENDING" | "MAPPED" | "REJECTED" | "APPROVED" | "GROUP_INVITE";

export type P2PTransfer = { id: string, transaction_id: string, direction: string, counterparty_name: string, counterparty_phone: string | null, counterparty_upi_id: string | null, is_merchant: boolean, upi_transaction_id: string | null, google_transaction_id: string | null, source_bank_account: string | null, };

export type Purchase = { id: string, transaction_id: string, vendor: string, total: string, order_id: string | null, };

export type PurchaseImport = { id: string, pdf_url: string, vendor: string, raw_content: string | null, };

export type PurchaseItem = { id: string, purchase_id: string, name: string, quantity: number, price: string, sku: string | null, };

export type Session = { id: string, expires_at: string, token: string, created_at: string, updated_at: string, ip_address: string | null, user_agent: string | null, user_id: string, };

export type StatementTxnMatch = { row_id: string, transaction_id: string, confidence: string, };

export type SubAlert = { id: string, subscription_id: string, days_before: number, sent_at: string | null, channel: string, };

export type Subscription = { id: string, user_id: string, name: string, amount: string, cycle: string, start_date: string, next_charge_date: string, detection_keywords: any, };

export type SubscriptionCharge = { id: string, subscription_id: string, transaction_id: string, charged_on: string, amount: string, status: string, };

export type SubscriptionCycle = "WEEKLY" | "MONTHLY" | "YEARLY";

export type Transaction = { id: string, user_id: string, amount: string, direction: TransactionDirection, date: string, source: TransactionSource, status: TransactionStatus, purpose_tag: string | null, group_id: string | null, source_wallet_id: string | null, destination_wallet_id: string | null, ledger_tab_id: string | null, deleted_at: string | null, };

export type TransactionDirection = "IN" | "OUT";

export type TransactionEdit = { id: string, transaction_id: string, old_amount: string, new_amount: string, edited_at: string, };

export type TransactionMetadata = { transaction_id: string, upi_txn_id: string | null, app_txn_id: string | null, app_name: string | null, contact_number: string | null, };

export type TransactionSource = "MANUAL" | "OCR" | "STATEMENT" | "P2P";

export type TransactionStatus = "COMPLETED" | "PENDING" | "CANCELLED";

export type TxnParty = { id: string, transaction_id: string, user_id: string | null, contact_id: string | null, role: string, };

export type TxnPartyRole = "SENDER" | "RECEIVER";

export type User = { id: string, name: string, email: string, email_verified: boolean, image: string | null, phone: string | null, is_active: boolean, created_at: string, updated_at: string, username: string | null, display_username: string | null, role: GroupRole | null, banned: boolean | null, ban_reason: string | null, ban_expires: string | null, two_factor_enabled: boolean | null, phone_number: string | null, phone_number_verified: boolean | null, metadata: any, associated_contact_id: string | null, };

export type UserGroup = { user_id: string, group_id: string, role: string, };

export type UserUpiId = { id: string, user_id: string, upi_id: string, is_primary: boolean, label: string | null, };

export type Verification = { id: string, identifier: string, value: string, expires_at: string, created_at: string | null, updated_at: string | null, };

export type Wallet = { id: string, user_id: string, name: string, type: string, balance: string, created_at: string, updated_at: string, };

export type WalletType = "CASH" | "BANK" | "CREDIT_CARD" | "UPI_WALLET";
