// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Specialized extraction for Google Pay screenshots.
 */
export type GPayExtraction = { amount: string, direction: string, datetime_str: string | null, status: string | null, counterparty_name: string, counterparty_phone: string | null, counterparty_upi_id: string | null, is_merchant: boolean, upi_transaction_id: string | null, google_transaction_id: string | null, source_bank_account: string | null, };
