// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A type alias for `serde_json::Value` to control its TypeScript export location.
 */
export type JsonValue = number | string | boolean | Array<JsonValue> | { [key: string]: JsonValue } | null;
