// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerTabStatus } from "./LedgerTabStatus";
import type { LedgerTabType } from "./LedgerTabType";

export type LedgerTab = { id: string, creator_id: string, counterparty_id: string | null, tab_type: LedgerTabType, title: string, target_amount: string, status: LedgerTabStatus, created_at: string, updated_at: string, description: string | null, };
