// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a single line item in a purchase, typically extracted via OCR.
 */
export type LineItem = { name: string, quantity: number, price: string, };
