// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trend data for a single month.
 */
export type MonthlyTrend = { month: string, income: string, expense: string, };
