// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Distribution of expenses by category or contact.
 */
export type NamedAmount = { name: string, amount: string, };
