// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OcrJobEdit = { id: string, ocr_job_id: string, user_id: string, field_name: string, original_value: string | null, corrected_value: string | null, created_at: string, };
