// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OcrJob = { id: string, user_id: string, status: string, r2_key: string, processed_data: import('./JsonValue').JsonValue, error: string | null, created_at: string, updated_at: string, };
