// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type P2PRequest = { id: string, sender_user_id: string, receiver_email: string, transaction_data: import('./JsonValue').JsonValue, status: string, linked_txn_id: string | null, };
