// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * P2P request with sender's name.
 */
export type P2PRequestWithSender = { sender_name: string | null, id: string, sender_user_id: string, receiver_email: string, transaction_data: any, status: string, linked_txn_id: string | null, };
