// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type P2PTransfer = { id: string, transaction_id: string, direction: string, counterparty_name: string, counterparty_phone: string | null, counterparty_upi_id: string | null, is_merchant: boolean, upi_transaction_id: string | null, google_transaction_id: string | null, source_bank_account: string | null, };
