// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified OCR data from the Python worker.
 */
export type ProcessedOcr = { doc_type: string, data: any, r2_key: string | null, };
