// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";

/**
 * Unified OCR data from the Python worker.
 */
export type ProcessedOcr = { doc_type: string, data: JsonValue, r2_key: string | null, };
