// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PurchaseImport = { id: string, pdf_url: string, vendor: string, raw_content: string | null, };
