// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpendingVelocity = { daily_burn_rate: number, target_daily_rate: number, is_overpacing: boolean, projected_total: number, };
