// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Details for splitting a transaction among multiple users.
 */
export type SplitDetail = { receiver_email: string, amount: string, };
