// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatementTxnMatch = { row_id: string, transaction_id: string, confidence: string, matched_at: string, };
