// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Subscription = { id: string, user_id: string, name: string, amount: string, cycle: string, start_date: string, next_charge_date: string, detection_keywords: any, };
