// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubscriptionCharge = { id: string, subscription_id: string, transaction_id: string, charged_on: string, amount: string, status: string, };
