// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransactionMetadata = { transaction_id: string | null, upi_txn_id: string | null, app_txn_id: string | null, app_name: string | null, contact_number: string | null, };
