// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TxnPartyRole } from "./TxnPartyRole";

export type TxnParty = { id: string, transaction_id: string, user_id: string | null, contact_id: string | null, role: TxnPartyRole, };
