// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";

export type User = { id: string, name: string, email: string, email_verified: boolean, image: string | null, phone: string | null, is_active: boolean, created_at: string, updated_at: string, username: string | null, display_username: string | null, role: string | null, banned: boolean | null, ban_reason: string | null, ban_expires: string | null, two_factor_enabled: boolean | null, phone_number: string | null, phone_number_verified: boolean | null, metadata: JsonValue | null, associated_contact_id: string | null, };
