// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupRole } from "./GroupRole";

export type UserGroup = { user_id: string, group_id: string, role: GroupRole, };
